# import Author2 from "author.gql"

type Book2 {
  title: String
  author: Author2
}

# interface Book {
#   title: String!
#   author: Author!
# }

# type Textbook implements Book {
#   title: String! # Must be present
#   author: Author! # Must be present
#   courses: [Course!]!
# }
