scalar Date

directive @upper on FIELD_DEFINITION

directive @rest(url: String) on FIELD_DEFINITION

type Query {
  me: User
  hero(name: String): Hero
  episode: Episode
  search: [SearchResult!]!
  characters: Character
  books: [Book!]!
  date: Date
  getDate(d: Date!): Date!
  hello: String @upper
  people: String @rest(url: "http://localhost:2021/movies/")
  movie(id: Int): Movie!
  mostViewedMovies: [Movie!]!
}

type Movie {
  message: String
  name: String
}

type Mutation {
  create(ri: ReviewInput): View
}

type Author {
  name: String!
}

type Course {
  name: String!
}

interface Book {
  title: String!
  author: Author!
}

type Textbook implements Book {
  title: String!
  author: Author!
  courses: [Course!]!
}

type ColoringBook implements Book {
  title: String!
  author: Author!
  colors: [String!]!
}

type User {
  id: ID
  name: String @deprecated(reason: "不用了")
}

type Hero {
  name: String
  friends: [Hero]
}

enum Episode {
  NEWHOPE
  EMPIRE
  JEDI
}

interface Character {
  id: ID!
  name: String!
}

type Human implements Character {
  id: ID!
  name: String!
  totalCredits: Int
}
 
type Droid implements Character {
  id: ID!
  name: String!
  primaryFunction: String
}

union SearchResult = Human | Droid

input ReviewInput {
  stars: Int!
  commentary: String
}

type View {
  stars: Int
}
