scalar Date

scalar Upload

directive @upper on FIELD_DEFINITION

directive @rest(url: String) on FIELD_DEFINITION

enum CacheControlScope {
  PUBLIC
  PRIVATE
}

directive @cacheControl(
  maxAge: Int
  scope: CacheControlScope
  inheritMaxAge: Boolean
) on FIELD_DEFINITION | OBJECT | INTERFACE | UNION

type Query {
  me: User @cacheControl(maxAge: 5)
  hero(name: String): Hero
  episode: Episode
  search: [SearchResult!]!
  characters: Character
  books: [Book!]!
  date: Date
  getDate(d: Date!): Date!
  hello: String @upper
  people: String @rest(url: "http://localhost:2021/movies/") @cacheControl(maxAge: 180)
  movie(id: Int): Movie! @cacheControl(maxAge: 180)
  mostViewedMovies: [Movie!]!
}

type Mutation {
  create(ri: ReviewInput): View
  createPost(author: String, comment: String): Post
  singleUpload(file: Upload!): File!
}

type Subscription {
  postCreated: Post
}

type File {
  filename: String!
  mimetype: String!
  encoding: String!
}

type Post {
  author: String
  comment: String
}

type Movie {
  message: String
  name: String
}

type Author {
  name: String!
}

type Course {
  name: String!
}

interface Book {
  title: String!
  author: Author!
}

type Textbook implements Book {
  title: String!
  author: Author!
  courses: [Course!]!
}

type ColoringBook implements Book {
  title: String!
  author: Author!
  colors: [String!]!
}

type User {
  id: ID
  name: String @deprecated(reason: "不用了")
}

type Hero {
  name: String
  friends: [Hero]
}

enum Episode {
  NEWHOPE
  EMPIRE
  JEDI
}

interface Character {
  id: ID!
  name: String!
}

type Human implements Character {
  id: ID!
  name: String!
  totalCredits: Int
}
 
type Droid implements Character {
  id: ID!
  name: String!
  primaryFunction: String
}

union SearchResult = Human | Droid

input ReviewInput {
  stars: Int!
  commentary: String
}

type View {
  stars: Int
}
