# import cacheControl from './directive.gql'

type Query {
  me: User @cacheControl(maxAge: 300)
}

type Mutation {
  login(user: UserInput): UserInfo
  register(info: RegisterInput): RegisterInfo
}

type RegisterInfo {
  code: String
  msg: String
}

type RegisterInput {
  username: String
  password: String
  code: String
}

input UserInput {
  username: String
  password: String
}

type UserInfo {
  username: String
  token: String
}

type User {
  id: ID @deprecated(reason: "不用了")
  name: String
}
